# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

from conanguide.ui.res import resources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1067, 800)
        MainWindow.setMinimumSize(QSize(800, 800))
        icon = QIcon()
        icon.addFile(u":/general/icon/conan_guide_icon.png", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setDockOptions(QMainWindow.AllowTabbedDocks|QMainWindow.AnimatedDocks)
        self.actionViewProfile = QAction(MainWindow)
        self.actionViewProfile.setObjectName(u"actionViewProfile")
        self.actionViewProfile.setChecked(False)
        icon1 = QIcon()
        icon1.addFile(u":/icon/light/conan_profile.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionViewProfile.setIcon(icon1)
        self.actionFileExit = QAction(MainWindow)
        self.actionFileExit.setObjectName(u"actionFileExit")
        self.actionRefresh = QAction(MainWindow)
        self.actionRefresh.setObjectName(u"actionRefresh")
        icon2 = QIcon()
        icon2.addFile(u":/icon/light/refresh.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionRefresh.setIcon(icon2)
        self.actionConanCreate = QAction(MainWindow)
        self.actionConanCreate.setObjectName(u"actionConanCreate")
        icon3 = QIcon()
        icon3.addFile(u":/icon/light/conan_create.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionConanCreate.setIcon(icon3)
        self.actionConanInstall = QAction(MainWindow)
        self.actionConanInstall.setObjectName(u"actionConanInstall")
        icon4 = QIcon()
        icon4.addFile(u":/icon/light/conan_install.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionConanInstall.setIcon(icon4)
        self.actionConanBuild = QAction(MainWindow)
        self.actionConanBuild.setObjectName(u"actionConanBuild")
        icon5 = QIcon()
        icon5.addFile(u":/icon/light/conan_build.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionConanBuild.setIcon(icon5)
        self.actionConanSource = QAction(MainWindow)
        self.actionConanSource.setObjectName(u"actionConanSource")
        icon6 = QIcon()
        icon6.addFile(u":/icon/light/conan_source.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionConanSource.setIcon(icon6)
        self.actionConanPackage = QAction(MainWindow)
        self.actionConanPackage.setObjectName(u"actionConanPackage")
        icon7 = QIcon()
        icon7.addFile(u":/icon/light/conan_package.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionConanPackage.setIcon(icon7)
        self.actionConanExport = QAction(MainWindow)
        self.actionConanExport.setObjectName(u"actionConanExport")
        icon8 = QIcon()
        icon8.addFile(u":/icon/light/conan_export.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionConanExport.setIcon(icon8)
        self.actionConanExportPackage = QAction(MainWindow)
        self.actionConanExportPackage.setObjectName(u"actionConanExportPackage")
        icon9 = QIcon()
        icon9.addFile(u":/icon/light/conan_package_export.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionConanExportPackage.setIcon(icon9)
        self.actionViewPackage = QAction(MainWindow)
        self.actionViewPackage.setObjectName(u"actionViewPackage")
        self.actionViewPackage.setChecked(False)
        icon10 = QIcon()
        icon10.addFile(u":/icon/light/package.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionViewPackage.setIcon(icon10)
        self.actionHelpConanio = QAction(MainWindow)
        self.actionHelpConanio.setObjectName(u"actionHelpConanio")
        icon11 = QIcon()
        icon11.addFile(u":/general/icon/conan_io_icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionHelpConanio.setIcon(icon11)
        self.actionHelpAbout = QAction(MainWindow)
        self.actionHelpAbout.setObjectName(u"actionHelpAbout")
        self.actionViewWorkspace = QAction(MainWindow)
        self.actionViewWorkspace.setObjectName(u"actionViewWorkspace")
        icon12 = QIcon()
        icon12.addFile(u":/icon/light/workspace.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionViewWorkspace.setIcon(icon12)
        self.actionViewRemote = QAction(MainWindow)
        self.actionViewRemote.setObjectName(u"actionViewRemote")
        icon13 = QIcon()
        icon13.addFile(u":/icon/light/conan_remote.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionViewRemote.setIcon(icon13)
        self.actionViewSettings = QAction(MainWindow)
        self.actionViewSettings.setObjectName(u"actionViewSettings")
        icon14 = QIcon()
        icon14.addFile(u":/icon/light/settings.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionViewSettings.setIcon(icon14)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout_12 = QVBoxLayout(self.centralwidget)
        self.verticalLayout_12.setSpacing(2)
        self.verticalLayout_12.setObjectName(u"verticalLayout_12")
        self.verticalLayout_12.setContentsMargins(2, 2, 2, 2)
        self.tabWidgetMain = QTabWidget(self.centralwidget)
        self.tabWidgetMain.setObjectName(u"tabWidgetMain")
        self.tabWidgetMain.setTabPosition(QTabWidget.West)
        self.tabWidgetMain.setTabShape(QTabWidget.Rounded)
        self.tabPackage = QWidget()
        self.tabPackage.setObjectName(u"tabPackage")
        self.horizontalLayout_4 = QHBoxLayout(self.tabPackage)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.splitter_5 = QSplitter(self.tabPackage)
        self.splitter_5.setObjectName(u"splitter_5")
        self.splitter_5.setOrientation(Qt.Horizontal)
        self.frame_6 = QFrame(self.splitter_5)
        self.frame_6.setObjectName(u"frame_6")
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setMinimumSize(QSize(300, 0))
        self.frame_6.setFrameShape(QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QFrame.Raised)
        self.verticalLayout = QVBoxLayout(self.frame_6)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.frame_16 = QFrame(self.frame_6)
        self.frame_16.setObjectName(u"frame_16")
        self.frame_16.setLayoutDirection(Qt.LeftToRight)
        self.frame_16.setFrameShape(QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_15 = QHBoxLayout(self.frame_16)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName(u"horizontalLayout_15")
        self.horizontalLayout_15.setContentsMargins(2, 2, 0, 2)
        self.checkBoxOpenExplorer = QToolButton(self.frame_16)
        self.checkBoxOpenExplorer.setObjectName(u"checkBoxOpenExplorer")
        self.checkBoxOpenExplorer.setMinimumSize(QSize(25, 25))
        self.checkBoxOpenExplorer.setMaximumSize(QSize(25, 25))
        icon15 = QIcon()
        icon15.addFile(u":/icon/light/open_folder.png", QSize(), QIcon.Normal, QIcon.Off)
        self.checkBoxOpenExplorer.setIcon(icon15)
        self.checkBoxOpenExplorer.setCheckable(True)
        self.checkBoxOpenExplorer.setChecked(True)

        self.horizontalLayout_15.addWidget(self.checkBoxOpenExplorer)

        self.checkBoxCopyClipboard = QToolButton(self.frame_16)
        self.checkBoxCopyClipboard.setObjectName(u"checkBoxCopyClipboard")
        self.checkBoxCopyClipboard.setMinimumSize(QSize(25, 25))
        self.checkBoxCopyClipboard.setMaximumSize(QSize(25, 25))
        icon16 = QIcon()
        icon16.addFile(u":/icon/light/copy.png", QSize(), QIcon.Normal, QIcon.Off)
        self.checkBoxCopyClipboard.setIcon(icon16)
        self.checkBoxCopyClipboard.setCheckable(True)
        self.checkBoxCopyClipboard.setChecked(True)

        self.horizontalLayout_15.addWidget(self.checkBoxCopyClipboard)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_15.addItem(self.horizontalSpacer)


        self.verticalLayout.addWidget(self.frame_16)

        self.splitter_3 = QSplitter(self.frame_6)
        self.splitter_3.setObjectName(u"splitter_3")
        self.splitter_3.setOrientation(Qt.Vertical)
        self.treeViewRecipe = QTreeView(self.splitter_3)
        self.treeViewRecipe.setObjectName(u"treeViewRecipe")
        self.treeViewRecipe.setEnabled(True)
        self.splitter_3.addWidget(self.treeViewRecipe)
        self.treeViewRecipeInspect = QTreeView(self.splitter_3)
        self.treeViewRecipeInspect.setObjectName(u"treeViewRecipeInspect")
        self.splitter_3.addWidget(self.treeViewRecipeInspect)

        self.verticalLayout.addWidget(self.splitter_3)

        self.splitter_5.addWidget(self.frame_6)
        self.frame_15 = QFrame(self.splitter_5)
        self.frame_15.setObjectName(u"frame_15")
        sizePolicy1 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(1)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.frame_15.sizePolicy().hasHeightForWidth())
        self.frame_15.setSizePolicy(sizePolicy1)
        self.frame_15.setFrameShape(QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QFrame.Raised)
        self.verticalLayout_13 = QVBoxLayout(self.frame_15)
        self.verticalLayout_13.setSpacing(5)
        self.verticalLayout_13.setObjectName(u"verticalLayout_13")
        self.verticalLayout_13.setContentsMargins(2, 2, 2, 2)
        self.splitter_6 = QSplitter(self.frame_15)
        self.splitter_6.setObjectName(u"splitter_6")
        self.splitter_6.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.splitter_6.setFrameShape(QFrame.NoFrame)
        self.splitter_6.setFrameShadow(QFrame.Plain)
        self.splitter_6.setLineWidth(1)
        self.splitter_6.setOrientation(Qt.Vertical)
        self.splitter_6.setHandleWidth(5)
        self.frame_19 = QFrame(self.splitter_6)
        self.frame_19.setObjectName(u"frame_19")
        self.frame_19.setMaximumSize(QSize(16777215, 135))
        self.frame_19.setFrameShape(QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QFrame.Raised)
        self.verticalLayout_14 = QVBoxLayout(self.frame_19)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName(u"verticalLayout_14")
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.groupBox = QGroupBox(self.frame_19)
        self.groupBox.setObjectName(u"groupBox")
        sizePolicy2 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy2)
        self.verticalLayout_8 = QVBoxLayout(self.groupBox)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.verticalLayout_8.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.verticalLayout_8.setContentsMargins(2, 2, 2, 2)
        self.frame = QFrame(self.groupBox)
        self.frame.setObjectName(u"frame")
        sizePolicy2.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy2)
        self.frame.setFrameShape(QFrame.NoFrame)
        self.frame.setFrameShadow(QFrame.Raised)
        self.horizontalLayout = QHBoxLayout(self.frame)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.label = QLabel(self.frame)
        self.label.setObjectName(u"label")
        self.label.setMinimumSize(QSize(75, 0))

        self.horizontalLayout.addWidget(self.label)

        self.lineEditCachePath = QLineEdit(self.frame)
        self.lineEditCachePath.setObjectName(u"lineEditCachePath")
        self.lineEditCachePath.setEnabled(True)
        self.lineEditCachePath.setReadOnly(True)

        self.horizontalLayout.addWidget(self.lineEditCachePath)

        self.btnCopyCachePath = QPushButton(self.frame)
        self.btnCopyCachePath.setObjectName(u"btnCopyCachePath")
        self.btnCopyCachePath.setIcon(icon16)

        self.horizontalLayout.addWidget(self.btnCopyCachePath)

        self.btnOpenCachePath = QPushButton(self.frame)
        self.btnOpenCachePath.setObjectName(u"btnOpenCachePath")
        self.btnOpenCachePath.setIcon(icon15)

        self.horizontalLayout.addWidget(self.btnOpenCachePath)


        self.verticalLayout_8.addWidget(self.frame)

        self.frame_21 = QFrame(self.groupBox)
        self.frame_21.setObjectName(u"frame_21")
        sizePolicy2.setHeightForWidth(self.frame_21.sizePolicy().hasHeightForWidth())
        self.frame_21.setSizePolicy(sizePolicy2)
        self.frame_21.setFrameShape(QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QFrame.Raised)
        self.frame_21.setLineWidth(1)
        self.horizontalLayout_21 = QHBoxLayout(self.frame_21)
        self.horizontalLayout_21.setSpacing(5)
        self.horizontalLayout_21.setObjectName(u"horizontalLayout_21")
        self.horizontalLayout_21.setContentsMargins(2, 2, 2, 2)
        self.label_20 = QLabel(self.frame_21)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setMinimumSize(QSize(75, 0))

        self.horizontalLayout_21.addWidget(self.label_20)

        self.lineEditDataPath = QLineEdit(self.frame_21)
        self.lineEditDataPath.setObjectName(u"lineEditDataPath")
        self.lineEditDataPath.setEnabled(True)
        self.lineEditDataPath.setReadOnly(True)

        self.horizontalLayout_21.addWidget(self.lineEditDataPath)

        self.btnCopyDataPath = QPushButton(self.frame_21)
        self.btnCopyDataPath.setObjectName(u"btnCopyDataPath")
        self.btnCopyDataPath.setIcon(icon16)

        self.horizontalLayout_21.addWidget(self.btnCopyDataPath)

        self.btnOpenDataPath = QPushButton(self.frame_21)
        self.btnOpenDataPath.setObjectName(u"btnOpenDataPath")
        self.btnOpenDataPath.setIcon(icon15)

        self.horizontalLayout_21.addWidget(self.btnOpenDataPath)


        self.verticalLayout_8.addWidget(self.frame_21)

        self.frame_2 = QFrame(self.groupBox)
        self.frame_2.setObjectName(u"frame_2")
        sizePolicy2.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy2)
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_2 = QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.label_2 = QLabel(self.frame_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setMinimumSize(QSize(75, 0))

        self.horizontalLayout_2.addWidget(self.label_2)

        self.lineEditRealPath = QLineEdit(self.frame_2)
        self.lineEditRealPath.setObjectName(u"lineEditRealPath")
        self.lineEditRealPath.setEnabled(True)
        self.lineEditRealPath.setReadOnly(True)

        self.horizontalLayout_2.addWidget(self.lineEditRealPath)

        self.btnCopyRealPath = QPushButton(self.frame_2)
        self.btnCopyRealPath.setObjectName(u"btnCopyRealPath")
        self.btnCopyRealPath.setIcon(icon16)

        self.horizontalLayout_2.addWidget(self.btnCopyRealPath)

        self.btnOpenRealPath = QPushButton(self.frame_2)
        self.btnOpenRealPath.setObjectName(u"btnOpenRealPath")
        self.btnOpenRealPath.setIcon(icon15)

        self.horizontalLayout_2.addWidget(self.btnOpenRealPath)


        self.verticalLayout_8.addWidget(self.frame_2)

        self.frame_3 = QFrame(self.groupBox)
        self.frame_3.setObjectName(u"frame_3")
        sizePolicy2.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy2)
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_3 = QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.label_3 = QLabel(self.frame_3)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setMinimumSize(QSize(75, 0))
        self.label_3.setBaseSize(QSize(0, 0))

        self.horizontalLayout_3.addWidget(self.label_3)

        self.lineEditPackagePath = QLineEdit(self.frame_3)
        self.lineEditPackagePath.setObjectName(u"lineEditPackagePath")
        self.lineEditPackagePath.setEnabled(True)
        self.lineEditPackagePath.setReadOnly(True)

        self.horizontalLayout_3.addWidget(self.lineEditPackagePath)

        self.btnCopyPackagePath = QPushButton(self.frame_3)
        self.btnCopyPackagePath.setObjectName(u"btnCopyPackagePath")
        self.btnCopyPackagePath.setIcon(icon16)

        self.horizontalLayout_3.addWidget(self.btnCopyPackagePath)

        self.btnOpenPackagePath = QPushButton(self.frame_3)
        self.btnOpenPackagePath.setObjectName(u"btnOpenPackagePath")
        self.btnOpenPackagePath.setIcon(icon15)

        self.horizontalLayout_3.addWidget(self.btnOpenPackagePath)


        self.verticalLayout_8.addWidget(self.frame_3)


        self.verticalLayout_14.addWidget(self.groupBox)

        self.splitter_6.addWidget(self.frame_19)
        self.frameWebView = QFrame(self.splitter_6)
        self.frameWebView.setObjectName(u"frameWebView")
        sizePolicy3 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(1)
        sizePolicy3.setHeightForWidth(self.frameWebView.sizePolicy().hasHeightForWidth())
        self.frameWebView.setSizePolicy(sizePolicy3)
        self.frameWebView.setFrameShape(QFrame.StyledPanel)
        self.frameWebView.setFrameShadow(QFrame.Raised)
        self.verticalLayout_7 = QVBoxLayout(self.frameWebView)
        self.verticalLayout_7.setSpacing(5)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.verticalLayout_7.setContentsMargins(2, 2, 2, 2)
        self.label_15 = QLabel(self.frameWebView)
        self.label_15.setObjectName(u"label_15")

        self.verticalLayout_7.addWidget(self.label_15)

        self.graphicsView = QGraphicsView(self.frameWebView)
        self.graphicsView.setObjectName(u"graphicsView")
        self.graphicsView.setSceneRect(QRectF(0, 0, 0, 0))

        self.verticalLayout_7.addWidget(self.graphicsView)

        self.splitter_6.addWidget(self.frameWebView)

        self.verticalLayout_13.addWidget(self.splitter_6)

        self.splitter_5.addWidget(self.frame_15)

        self.horizontalLayout_4.addWidget(self.splitter_5)

        icon17 = QIcon()
        icon17.addFile(u":/icon/light/tab_package.png", QSize(), QIcon.Normal, QIcon.Off)
        self.tabWidgetMain.addTab(self.tabPackage, icon17, "")
        self.tabWorkspace = QWidget()
        self.tabWorkspace.setObjectName(u"tabWorkspace")
        self.verticalLayout_6 = QVBoxLayout(self.tabWorkspace)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.splitter_8 = QSplitter(self.tabWorkspace)
        self.splitter_8.setObjectName(u"splitter_8")
        self.splitter_8.setOrientation(Qt.Vertical)
        self.frame_24 = QFrame(self.splitter_8)
        self.frame_24.setObjectName(u"frame_24")
        self.frame_24.setMaximumSize(QSize(16777215, 228))
        self.frame_24.setFrameShape(QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QFrame.Raised)
        self.verticalLayout_3 = QVBoxLayout(self.frame_24)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.frame_4 = QFrame(self.frame_24)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_5 = QHBoxLayout(self.frame_4)
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(2, 2, 2, 2)
        self.label_4 = QLabel(self.frame_4)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setMinimumSize(QSize(75, 0))

        self.horizontalLayout_5.addWidget(self.label_4)

        self.lineEditUser = QLineEdit(self.frame_4)
        self.lineEditUser.setObjectName(u"lineEditUser")

        self.horizontalLayout_5.addWidget(self.lineEditUser)

        self.label_14 = QLabel(self.frame_4)
        self.label_14.setObjectName(u"label_14")

        self.horizontalLayout_5.addWidget(self.label_14)

        self.label_13 = QLabel(self.frame_4)
        self.label_13.setObjectName(u"label_13")

        self.horizontalLayout_5.addWidget(self.label_13)

        self.lineEditChannel = QLineEdit(self.frame_4)
        self.lineEditChannel.setObjectName(u"lineEditChannel")

        self.horizontalLayout_5.addWidget(self.lineEditChannel)


        self.verticalLayout_3.addWidget(self.frame_4)

        self.frame_8 = QFrame(self.frame_24)
        self.frame_8.setObjectName(u"frame_8")
        self.frame_8.setFrameShape(QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_6 = QHBoxLayout(self.frame_8)
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.horizontalLayout_6.setContentsMargins(2, 2, 2, 2)
        self.label_5 = QLabel(self.frame_8)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setMinimumSize(QSize(75, 0))

        self.horizontalLayout_6.addWidget(self.label_5)

        self.lineEditRecipePath = QLineEdit(self.frame_8)
        self.lineEditRecipePath.setObjectName(u"lineEditRecipePath")
        self.lineEditRecipePath.setMinimumSize(QSize(0, 0))
        self.lineEditRecipePath.setReadOnly(False)

        self.horizontalLayout_6.addWidget(self.lineEditRecipePath)

        self.toolBtnExplorerRecipePath = QToolButton(self.frame_8)
        self.toolBtnExplorerRecipePath.setObjectName(u"toolBtnExplorerRecipePath")
        sizePolicy4 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.toolBtnExplorerRecipePath.sizePolicy().hasHeightForWidth())
        self.toolBtnExplorerRecipePath.setSizePolicy(sizePolicy4)
        self.toolBtnExplorerRecipePath.setMinimumSize(QSize(0, 0))

        self.horizontalLayout_6.addWidget(self.toolBtnExplorerRecipePath)


        self.verticalLayout_3.addWidget(self.frame_8)

        self.frame_9 = QFrame(self.frame_24)
        self.frame_9.setObjectName(u"frame_9")
        self.frame_9.setFrameShape(QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_7 = QHBoxLayout(self.frame_9)
        self.horizontalLayout_7.setSpacing(5)
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.horizontalLayout_7.setContentsMargins(2, 2, 2, 2)
        self.label_6 = QLabel(self.frame_9)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setMinimumSize(QSize(75, 0))

        self.horizontalLayout_7.addWidget(self.label_6)

        self.lineEditInstallPath = QLineEdit(self.frame_9)
        self.lineEditInstallPath.setObjectName(u"lineEditInstallPath")

        self.horizontalLayout_7.addWidget(self.lineEditInstallPath)

        self.toolBtnExplorerInstallPath = QToolButton(self.frame_9)
        self.toolBtnExplorerInstallPath.setObjectName(u"toolBtnExplorerInstallPath")

        self.horizontalLayout_7.addWidget(self.toolBtnExplorerInstallPath)


        self.verticalLayout_3.addWidget(self.frame_9)

        self.frame_10 = QFrame(self.frame_24)
        self.frame_10.setObjectName(u"frame_10")
        self.frame_10.setFrameShape(QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_8 = QHBoxLayout(self.frame_10)
        self.horizontalLayout_8.setSpacing(5)
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.horizontalLayout_8.setContentsMargins(2, 2, 2, 2)
        self.label_7 = QLabel(self.frame_10)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setMinimumSize(QSize(75, 0))

        self.horizontalLayout_8.addWidget(self.label_7)

        self.lineEditBuildPath = QLineEdit(self.frame_10)
        self.lineEditBuildPath.setObjectName(u"lineEditBuildPath")

        self.horizontalLayout_8.addWidget(self.lineEditBuildPath)

        self.toolBtnExplorerBuildPath = QToolButton(self.frame_10)
        self.toolBtnExplorerBuildPath.setObjectName(u"toolBtnExplorerBuildPath")

        self.horizontalLayout_8.addWidget(self.toolBtnExplorerBuildPath)


        self.verticalLayout_3.addWidget(self.frame_10)

        self.frame_11 = QFrame(self.frame_24)
        self.frame_11.setObjectName(u"frame_11")
        self.frame_11.setFrameShape(QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_9 = QHBoxLayout(self.frame_11)
        self.horizontalLayout_9.setSpacing(5)
        self.horizontalLayout_9.setObjectName(u"horizontalLayout_9")
        self.horizontalLayout_9.setContentsMargins(2, 2, 2, 2)
        self.label_8 = QLabel(self.frame_11)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setMinimumSize(QSize(75, 0))

        self.horizontalLayout_9.addWidget(self.label_8)

        self.lineEditSourcePath = QLineEdit(self.frame_11)
        self.lineEditSourcePath.setObjectName(u"lineEditSourcePath")

        self.horizontalLayout_9.addWidget(self.lineEditSourcePath)

        self.toolBtnExplorerSourcePath = QToolButton(self.frame_11)
        self.toolBtnExplorerSourcePath.setObjectName(u"toolBtnExplorerSourcePath")

        self.horizontalLayout_9.addWidget(self.toolBtnExplorerSourcePath)


        self.verticalLayout_3.addWidget(self.frame_11)

        self.frame_13 = QFrame(self.frame_24)
        self.frame_13.setObjectName(u"frame_13")
        self.frame_13.setFrameShape(QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_12 = QHBoxLayout(self.frame_13)
        self.horizontalLayout_12.setSpacing(5)
        self.horizontalLayout_12.setObjectName(u"horizontalLayout_12")
        self.horizontalLayout_12.setContentsMargins(2, 2, 2, 2)
        self.label_11 = QLabel(self.frame_13)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setMinimumSize(QSize(75, 0))

        self.horizontalLayout_12.addWidget(self.label_11)

        self.lineEditPackageExpPath = QLineEdit(self.frame_13)
        self.lineEditPackageExpPath.setObjectName(u"lineEditPackageExpPath")

        self.horizontalLayout_12.addWidget(self.lineEditPackageExpPath)

        self.toolBtnExplorerPackagePath = QToolButton(self.frame_13)
        self.toolBtnExplorerPackagePath.setObjectName(u"toolBtnExplorerPackagePath")

        self.horizontalLayout_12.addWidget(self.toolBtnExplorerPackagePath)


        self.verticalLayout_3.addWidget(self.frame_13)

        self.frame_12 = QFrame(self.frame_24)
        self.frame_12.setObjectName(u"frame_12")
        self.frame_12.setFrameShape(QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_10 = QHBoxLayout(self.frame_12)
        self.horizontalLayout_10.setSpacing(5)
        self.horizontalLayout_10.setObjectName(u"horizontalLayout_10")
        self.horizontalLayout_10.setContentsMargins(2, 2, 2, 2)
        self.label_9 = QLabel(self.frame_12)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setMinimumSize(QSize(75, 0))

        self.horizontalLayout_10.addWidget(self.label_9)

        self.lineEditAdditionalParams = QLineEdit(self.frame_12)
        self.lineEditAdditionalParams.setObjectName(u"lineEditAdditionalParams")

        self.horizontalLayout_10.addWidget(self.lineEditAdditionalParams)


        self.verticalLayout_3.addWidget(self.frame_12)

        self.frame_14 = QFrame(self.frame_24)
        self.frame_14.setObjectName(u"frame_14")
        self.frame_14.setFrameShape(QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_13 = QHBoxLayout(self.frame_14)
        self.horizontalLayout_13.setSpacing(5)
        self.horizontalLayout_13.setObjectName(u"horizontalLayout_13")
        self.horizontalLayout_13.setContentsMargins(2, 2, 2, 2)
        self.label_12 = QLabel(self.frame_14)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setMinimumSize(QSize(75, 0))
        self.label_12.setMaximumSize(QSize(50, 16777215))

        self.horizontalLayout_13.addWidget(self.label_12)

        self.comboBoxProfile = QComboBox(self.frame_14)
        self.comboBoxProfile.setObjectName(u"comboBoxProfile")

        self.horizontalLayout_13.addWidget(self.comboBoxProfile)


        self.verticalLayout_3.addWidget(self.frame_14)

        self.splitter_8.addWidget(self.frame_24)
        self.frame_25 = QFrame(self.splitter_8)
        self.frame_25.setObjectName(u"frame_25")
        sizePolicy3.setHeightForWidth(self.frame_25.sizePolicy().hasHeightForWidth())
        self.frame_25.setSizePolicy(sizePolicy3)
        self.frame_25.setFrameShape(QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_17 = QHBoxLayout(self.frame_25)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName(u"horizontalLayout_17")
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.groupBox_4 = QGroupBox(self.frame_25)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.horizontalLayout_18 = QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_18.setSpacing(2)
        self.horizontalLayout_18.setObjectName(u"horizontalLayout_18")
        self.horizontalLayout_18.setContentsMargins(2, 2, 2, 2)
        self.frame_5 = QFrame(self.groupBox_4)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setFrameShape(QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Raised)
        self.verticalLayout_5 = QVBoxLayout(self.frame_5)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.toolButtonClearConsole = QToolButton(self.frame_5)
        self.toolButtonClearConsole.setObjectName(u"toolButtonClearConsole")
        self.toolButtonClearConsole.setMinimumSize(QSize(25, 25))
        icon18 = QIcon()
        icon18.addFile(u":/icon/light/garbage_can.png", QSize(), QIcon.Normal, QIcon.Off)
        self.toolButtonClearConsole.setIcon(icon18)
        self.toolButtonClearConsole.setCheckable(False)

        self.verticalLayout_5.addWidget(self.toolButtonClearConsole)

        self.toolButtonConsoleScrollToEnd = QToolButton(self.frame_5)
        self.toolButtonConsoleScrollToEnd.setObjectName(u"toolButtonConsoleScrollToEnd")
        self.toolButtonConsoleScrollToEnd.setMinimumSize(QSize(25, 25))
        icon19 = QIcon()
        icon19.addFile(u":/icon/light/scroll_to_end.png", QSize(), QIcon.Normal, QIcon.Off)
        self.toolButtonConsoleScrollToEnd.setIcon(icon19)
        self.toolButtonConsoleScrollToEnd.setCheckable(True)
        self.toolButtonConsoleScrollToEnd.setChecked(True)

        self.verticalLayout_5.addWidget(self.toolButtonConsoleScrollToEnd)

        self.verticalSpacer_2 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.verticalLayout_5.addItem(self.verticalSpacer_2)


        self.horizontalLayout_18.addWidget(self.frame_5)

        self.console = QPlainTextEdit(self.groupBox_4)
        self.console.setObjectName(u"console")
        font = QFont()
        font.setFamily(u"Consolas")
        font.setPointSize(8)
        self.console.setFont(font)
        self.console.setReadOnly(True)
        self.console.setTextInteractionFlags(Qt.TextSelectableByMouse)
        self.console.setCenterOnScroll(False)

        self.horizontalLayout_18.addWidget(self.console)


        self.horizontalLayout_17.addWidget(self.groupBox_4)

        self.splitter_8.addWidget(self.frame_25)

        self.verticalLayout_6.addWidget(self.splitter_8)

        icon20 = QIcon()
        icon20.addFile(u":/icon/light/tab_workspace.png", QSize(), QIcon.Normal, QIcon.Off)
        self.tabWidgetMain.addTab(self.tabWorkspace, icon20, "")
        self.tabProfile = QWidget()
        self.tabProfile.setObjectName(u"tabProfile")
        self.layoutTabProfile = QHBoxLayout(self.tabProfile)
        self.layoutTabProfile.setSpacing(0)
        self.layoutTabProfile.setObjectName(u"layoutTabProfile")
        self.layoutTabProfile.setContentsMargins(0, 0, 0, 0)
        icon21 = QIcon()
        icon21.addFile(u":/icon/light/tab_conan_profile.png", QSize(), QIcon.Normal, QIcon.Off)
        self.tabWidgetMain.addTab(self.tabProfile, icon21, "")
        self.tabRemote = QWidget()
        self.tabRemote.setObjectName(u"tabRemote")
        self.verticalLayout_4 = QVBoxLayout(self.tabRemote)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(2, 2, 2, 2)
        self.frame_7 = QFrame(self.tabRemote)
        self.frame_7.setObjectName(u"frame_7")
        self.frame_7.setFrameShape(QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_16 = QHBoxLayout(self.frame_7)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName(u"horizontalLayout_16")
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.toolButton = QToolButton(self.frame_7)
        self.toolButton.setObjectName(u"toolButton")
        self.toolButton.setMinimumSize(QSize(25, 25))
        self.toolButton.setMaximumSize(QSize(20, 16777215))
        icon22 = QIcon()
        icon22.addFile(u":/icon/light/add.png", QSize(), QIcon.Normal, QIcon.Off)
        self.toolButton.setIcon(icon22)

        self.horizontalLayout_16.addWidget(self.toolButton)

        self.toolButton_2 = QToolButton(self.frame_7)
        self.toolButton_2.setObjectName(u"toolButton_2")
        sizePolicy4.setHeightForWidth(self.toolButton_2.sizePolicy().hasHeightForWidth())
        self.toolButton_2.setSizePolicy(sizePolicy4)
        self.toolButton_2.setMinimumSize(QSize(25, 25))
        icon23 = QIcon()
        icon23.addFile(u":/icon/light/remove.png", QSize(), QIcon.Normal, QIcon.Off)
        self.toolButton_2.setIcon(icon23)

        self.horizontalLayout_16.addWidget(self.toolButton_2)

        self.horizontalSpacer_2 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_16.addItem(self.horizontalSpacer_2)


        self.verticalLayout_4.addWidget(self.frame_7)

        self.tableViewRemoteList = QTableView(self.tabRemote)
        self.tableViewRemoteList.setObjectName(u"tableViewRemoteList")
        self.tableViewRemoteList.setHorizontalScrollMode(QAbstractItemView.ScrollPerPixel)

        self.verticalLayout_4.addWidget(self.tableViewRemoteList)

        icon24 = QIcon()
        icon24.addFile(u":/icon/light/tab_conan_remote.png", QSize(), QIcon.Normal, QIcon.Off)
        self.tabWidgetMain.addTab(self.tabRemote, icon24, "")
        self.tabSettings = QWidget()
        self.tabSettings.setObjectName(u"tabSettings")
        icon25 = QIcon()
        icon25.addFile(u":/icon/light/tab_settings.png", QSize(), QIcon.Normal, QIcon.Off)
        self.tabWidgetMain.addTab(self.tabSettings, icon25, "")

        self.verticalLayout_12.addWidget(self.tabWidgetMain)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1067, 21))
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuConan = QMenu(self.menubar)
        self.menuConan.setObjectName(u"menuConan")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QStatusBar(MainWindow)
        self.statusBar.setObjectName(u"statusBar")
        self.statusBar.setMaximumSize(QSize(16777215, 16777215))
        MainWindow.setStatusBar(self.statusBar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        sizePolicy4.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy4)
        self.toolBar.setMinimumSize(QSize(0, 0))
        self.toolBar.setBaseSize(QSize(0, 50))
        self.toolBar.setMovable(False)
        self.toolBar.setIconSize(QSize(30, 30))
        self.toolBar.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.toolBar.setFloatable(False)
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuConan.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuView.addAction(self.actionViewPackage)
        self.menuView.addAction(self.actionViewWorkspace)
        self.menuView.addAction(self.actionViewProfile)
        self.menuView.addAction(self.actionViewRemote)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionViewSettings)
        self.menuFile.addAction(self.actionRefresh)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionFileExit)
        self.menuHelp.addAction(self.actionHelpConanio)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionHelpAbout)
        self.menuConan.addAction(self.actionConanCreate)
        self.menuConan.addAction(self.actionConanInstall)
        self.menuConan.addAction(self.actionConanBuild)
        self.menuConan.addAction(self.actionConanSource)
        self.menuConan.addAction(self.actionConanPackage)
        self.menuConan.addAction(self.actionConanExport)
        self.menuConan.addAction(self.actionConanExportPackage)
        self.toolBar.addAction(self.actionRefresh)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionConanCreate)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionConanInstall)
        self.toolBar.addAction(self.actionConanBuild)
        self.toolBar.addAction(self.actionConanSource)
        self.toolBar.addAction(self.actionConanPackage)
        self.toolBar.addAction(self.actionConanExport)
        self.toolBar.addAction(self.actionConanExportPackage)

        self.retranslateUi(MainWindow)
        self.actionFileExit.triggered.connect(MainWindow.close)
        self.toolButtonClearConsole.pressed.connect(self.console.clear)

        self.tabWidgetMain.setCurrentIndex(2)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Conan GUIde", None))
        self.actionViewProfile.setText(QCoreApplication.translate("MainWindow", u"Profile", None))
#if QT_CONFIG(shortcut)
        self.actionViewProfile.setShortcut(QCoreApplication.translate("MainWindow", u"Alt+3", None))
#endif // QT_CONFIG(shortcut)
        self.actionFileExit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
#if QT_CONFIG(shortcut)
        self.actionFileExit.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Q", None))
#endif // QT_CONFIG(shortcut)
        self.actionRefresh.setText(QCoreApplication.translate("MainWindow", u"Refresh", None))
#if QT_CONFIG(shortcut)
        self.actionRefresh.setShortcut(QCoreApplication.translate("MainWindow", u"F5", None))
#endif // QT_CONFIG(shortcut)
        self.actionConanCreate.setText(QCoreApplication.translate("MainWindow", u"Create", None))
#if QT_CONFIG(shortcut)
        self.actionConanCreate.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+C", None))
#endif // QT_CONFIG(shortcut)
        self.actionConanInstall.setText(QCoreApplication.translate("MainWindow", u"Install", None))
#if QT_CONFIG(shortcut)
        self.actionConanInstall.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+I", None))
#endif // QT_CONFIG(shortcut)
        self.actionConanBuild.setText(QCoreApplication.translate("MainWindow", u"Build", None))
#if QT_CONFIG(shortcut)
        self.actionConanBuild.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+B", None))
#endif // QT_CONFIG(shortcut)
        self.actionConanSource.setText(QCoreApplication.translate("MainWindow", u"Source", None))
#if QT_CONFIG(shortcut)
        self.actionConanSource.setShortcut(QCoreApplication.translate("MainWindow", u"Alt+Shift+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionConanPackage.setText(QCoreApplication.translate("MainWindow", u"Package", None))
#if QT_CONFIG(shortcut)
        self.actionConanPackage.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+P", None))
#endif // QT_CONFIG(shortcut)
        self.actionConanExport.setText(QCoreApplication.translate("MainWindow", u"Export", None))
#if QT_CONFIG(shortcut)
        self.actionConanExport.setShortcut(QCoreApplication.translate("MainWindow", u"Alt+Shift+E", None))
#endif // QT_CONFIG(shortcut)
        self.actionConanExportPackage.setText(QCoreApplication.translate("MainWindow", u"Export Package", None))
#if QT_CONFIG(shortcut)
        self.actionConanExportPackage.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+E", None))
#endif // QT_CONFIG(shortcut)
        self.actionViewPackage.setText(QCoreApplication.translate("MainWindow", u"Package", None))
#if QT_CONFIG(tooltip)
        self.actionViewPackage.setToolTip(QCoreApplication.translate("MainWindow", u"Package", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionViewPackage.setShortcut(QCoreApplication.translate("MainWindow", u"Alt+1", None))
#endif // QT_CONFIG(shortcut)
        self.actionHelpConanio.setText(QCoreApplication.translate("MainWindow", u"conan.io", None))
#if QT_CONFIG(shortcut)
        self.actionHelpConanio.setShortcut(QCoreApplication.translate("MainWindow", u"F3", None))
#endif // QT_CONFIG(shortcut)
        self.actionHelpAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
#if QT_CONFIG(shortcut)
        self.actionHelpAbout.setShortcut(QCoreApplication.translate("MainWindow", u"F4", None))
#endif // QT_CONFIG(shortcut)
        self.actionViewWorkspace.setText(QCoreApplication.translate("MainWindow", u"Workspace", None))
#if QT_CONFIG(shortcut)
        self.actionViewWorkspace.setShortcut(QCoreApplication.translate("MainWindow", u"Alt+2", None))
#endif // QT_CONFIG(shortcut)
        self.actionViewRemote.setText(QCoreApplication.translate("MainWindow", u"Remote", None))
#if QT_CONFIG(shortcut)
        self.actionViewRemote.setShortcut(QCoreApplication.translate("MainWindow", u"Alt+4", None))
#endif // QT_CONFIG(shortcut)
        self.actionViewSettings.setText(QCoreApplication.translate("MainWindow", u"Settings", None))
#if QT_CONFIG(shortcut)
        self.actionViewSettings.setShortcut(QCoreApplication.translate("MainWindow", u"Alt+S", None))
#endif // QT_CONFIG(shortcut)
        self.checkBoxOpenExplorer.setText("")
        self.checkBoxCopyClipboard.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Local Cache", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Cache Path", None))
        self.btnCopyCachePath.setText(QCoreApplication.translate("MainWindow", u"Copy", None))
        self.btnOpenCachePath.setText(QCoreApplication.translate("MainWindow", u" Open", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"Data Path", None))
        self.btnCopyDataPath.setText(QCoreApplication.translate("MainWindow", u"Copy", None))
        self.btnOpenDataPath.setText(QCoreApplication.translate("MainWindow", u" Open", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Real Path", None))
        self.btnCopyRealPath.setText(QCoreApplication.translate("MainWindow", u"Copy", None))
        self.btnOpenRealPath.setText(QCoreApplication.translate("MainWindow", u" Open", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Package Path", None))
        self.btnCopyPackagePath.setText(QCoreApplication.translate("MainWindow", u"Copy", None))
        self.btnOpenPackagePath.setText(QCoreApplication.translate("MainWindow", u" Open", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Dependencies Graph", None))
        self.tabWidgetMain.setTabText(self.tabWidgetMain.indexOf(self.tabPackage), QCoreApplication.translate("MainWindow", u"Package", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"User", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"/", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Channel", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Recipe Path", None))
        self.toolBtnExplorerRecipePath.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Install Path", None))
        self.toolBtnExplorerInstallPath.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Build Path", None))
        self.toolBtnExplorerBuildPath.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Source Path", None))
        self.toolBtnExplorerSourcePath.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Package Path", None))
        self.toolBtnExplorerPackagePath.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Parameter", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Profile", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"Console", None))
        self.toolButtonClearConsole.setText("")
        self.toolButtonConsoleScrollToEnd.setText("")
        self.console.setPlainText("")
        self.tabWidgetMain.setTabText(self.tabWidgetMain.indexOf(self.tabWorkspace), QCoreApplication.translate("MainWindow", u"Workspace", None))
        self.tabWidgetMain.setTabText(self.tabWidgetMain.indexOf(self.tabProfile), QCoreApplication.translate("MainWindow", u"Profile", None))
        self.toolButton.setText("")
        self.toolButton_2.setText("")
        self.tabWidgetMain.setTabText(self.tabWidgetMain.indexOf(self.tabRemote), QCoreApplication.translate("MainWindow", u"Remote", None))
        self.tabWidgetMain.setTabText(self.tabWidgetMain.indexOf(self.tabSettings), QCoreApplication.translate("MainWindow", u"Settings", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.menuConan.setTitle(QCoreApplication.translate("MainWindow", u"Conan", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
    # retranslateUi

